### ISSUE TITLE
VexRiscv-Min variant misbheaving

### ISSUE THREAD

**Issue by smunaut** [m-labs/VexRiscv-verilog#7] opened 2019-05-18 08:38 UTC
Swapping between the Min and Lite variant produces drastically different results.

AFAICT the 'Min' variant is skipping some instructions, executing some of them twice (I see doubled up memory writes), ...

All on very simple design with just one bram connected to instruction port and one to the data port.

Has anyone run the -Min variant ?

**Comment by Dolu1990** [comment] 2019-05-18 10:08
Hi,

I just tester the Min variant on the VexRiscv regression tool (the main difference against lite is that the min isn't using the instruction cache).

And it passed all the test i can run on it, including dhrystone and coremark.
So, as far i can see, if there is an issue, it could be : 
- The wishbone stimulus in my testbench aren't compliant to wishbone
- The wisnbone stimuls in my testbench do not cover enough state spaces
- Your testbench has issue.

I'm not a wishbone expert at all.
Can you send me your wave ? and point me when you see the issue ?

**Comment by smunaut** [comment] 2019-05-18 11:14
[bug.tar.gz](https://github.com/m-labs/VexRiscv-verilog/files/3193985/bug.tar.gz)

Included a minimal setup.

If you look at t=4.8 us and t=4.9 us   two writes to 0x2080000D (which is 32 bit address 0x82000034)
This is the instruction @ 0xc4 ( 0x31 word address ) being executed twice:

```
000000bc <_spi_do_one>:
  bc:	820002b7          	lui	t0,0x82000
  c0:	00800313          	li	t1,8
  c4:	02a2aa23          	sw	a0,52(t0) # 82000034 <SPI_BASE+0x34>
  c8:	0302a503          	lw	a0,48(t0)
  cc:	00657533          	and	a0,a0,t1
  d0:	fe651ce3          	bne	a0,t1,c8 <_spi_do_one+0xc>
  d4:	0382a503          	lw	a0,56(t0)
  d8:	00008067          	ret
```
And if you look at the iBus, you can see that 0x31 (=0xc4) is fetched twice. You can also see that 0x2f ( = 0xbc ) which is the start of that function is actually never fetched ...

**Comment by Dolu1990** [comment] 2019-05-18 13:13
Thanks !

So. i suspect that's a Icarus simulator  bug. I already had quite a few issue with it XD

There is the proof, please double verify that i'm not saying bullshit :

From VexRiscv_Min.v
```verilog
  always @ (*) begin
    IBusSimplePlugin_iBusRsp_stages_0_halt = 1'b0;
    if((IBusSimplePlugin_iBusRsp_stages_0_input_valid && ((! IBusSimplePlugin_cmd_valid) || (! IBusSimplePlugin_cmd_ready))))begin
      IBusSimplePlugin_iBusRsp_stages_0_halt = 1'b1;
    end
    IBusSimplePlugin_cmd_valid = ((IBusSimplePlugin_iBusRsp_stages_0_input_valid && IBusSimplePlugin_iBusRsp_stages_0_output_ready) && (IBusSimplePlugin_pendingCmd != (3'b111)));
    if((IBusSimplePlugin_mmuBus_rsp_exception || IBusSimplePlugin_mmuBus_rsp_refilling))begin
      IBusSimplePlugin_iBusRsp_stages_0_halt = 1'b0;
      IBusSimplePlugin_cmd_valid = 1'b0;
    end
  end
```

The only way for IBusSimplePlugin_iBusRsp_stages_0_halt  to be set, is to have the given conditition set : 
(IBusSimplePlugin_iBusRsp_stages_0_input_valid && ((! IBusSimplePlugin_cmd_valid) || (! IBusSimplePlugin_cmd_ready)))

Wave which point the moment at which the simulator seem to do crap : 
![image](https://user-images.githubusercontent.com/4832082/57970187-b1f56380-797e-11e9-82d8-6c367ebdba4e.png)

Please, again, double check my proof. And in any case, thanks for the report :)
Which version of icarus verilog are you using ? I remember i had to avoid the the 9.7 which was buggy.

**Comment by smunaut** [comment] 2019-05-18 13:37
Huh ... I'm not so sure about that. I think this might me one of the "undetermined" case of verilog because in that always(*) process, you assign BusSimplePlugin_cmd_valid  _after_ you check its value for IBusSimplePlugin_iBusRsp_stages_0_halt  and I'm not sure the semantic of verilog forces the simulator to re-rerun the process.

If I move the IBusSimplePlugin_cmd_valid assignement at the beginning of the process, it seems to fix the issue.

**Comment by sbourdeauducq** [comment] 2019-05-18 13:46
More generally, I'm quite concerned about the use of blocking assignments on signals that are used in multiple ``always`` blocks. In the general case, the result of the simulation then depends on the run order of  ``always`` blocks that respond to the same trigger, which is implementation-dependent (and sometimes modified by innocuous-looking changes in the code, which makes for insanely frustrating debugging sessions). Or does SpinalHDL ensure that this is not the case?

**Comment by Dolu1990** [comment] 2019-05-18 14:39
Honnestly, if that was only about my opinion, i would always use  nonblocking Assignment for both combinatorial and syncronous always blocks.

But when i was implementing the verilog backend of SpinalHDL, (I'm a VHDL guy), i looked to online ressource to look how always blocks should be done , and often you see "Use only blocking assignement in always( * )"
For instance https://class.ece.uw.edu/371/peckol/doc/Always@.pdf

```
1.5 always@( * ) Blocks
always@( * ) blocks are used to describe Combinational Logic, or Logic Gates. Only = (blocking)
assignments should be used in an always@( * ) block. Never use <= (non-blocking) assignments in
always@( * ) blocks. Only use always@( * ) block when you want to infer an element(s) that changes
its value as soon as one or more of its inputs change.
```

As far i know, the simulator should rerun a always block when one of its dependancies was assigned somewhere. Take the case of one always block which use the result of a chaine of 2 always blocks, and the result of a chaine of 3 always blocks. This can easily happen in RTL, and should provoke multiple "transiant" over multiple delta cycles before stabilizing, but all of this durring a single time.  (that's from a VHDL perspective, but verilog simulators shouldn't be so far in practice to be usefull ?)

> Or does SpinalHDL ensure that this is not the case?

No it do not ensure it. because it does the assumption that the rule i described in the above paragraph are respected by the simulator. If it is the case, the values should stabilize in a deterministic manner. Shouldn't it ? But for sure, the values transients during the delta cycle of a given time simulation aren't deterministic. but that shouldn't matter.


@smunaut which version of iverilog are you using ?

**Comment by smunaut** [comment] 2019-05-18 14:46
I use iverilog 10.2

Yes you should use blocking assignement for combinatorial blocks, but ideally you should not have "loops" of those always block depending on each other (including a block depending on itself). If that's an option, I would just generate 1 always block for each assigned variable.

I've been reading the specs and ... I'm really still not sure. Because at some point they talk about assignement (and not update, assignement, so that would include assignement of the same value as before) trigerring process ... but then you have infinite loops so that would make sense that the process generating the assignement event is excluded. 

All in all ... I'm not sure who's at fault, but I would just avoid generating those cases all together if possible.

**Comment by Dolu1990** [comment] 2019-05-18 15:05
> 1 always block for each assigned variable.
If you wanna try => 

https://github.com/m-labs/VexRiscv-verilog/blob/master/src/main/scala/vexriscv/GenCoreDefault.scala#L14

```scala
  defaultConfigForClockDomains = ClockDomainConfig(
    mergeAsyncProcess = false,
    resetKind = spinal.core.SYNC
  )
``` 

>All in all ... I'm not sure who's at fault, but I would just avoid generating those cases all together if possible.
I will check if i can make a fix to avoid merging "AsyncProcess" which result into the assignement of a dependancy. Should be fesable without to much paine.

Thanks for the help :D

**Comment by smunaut** [comment] 2019-05-18 16:51
I can't get `mergeAsyncProcess` to build at all.

This is what my last attempt looks like : (because AFAICT that setting isn't on ClockDomainConfig, but on SpinalConfig) : 

```diff
diff --git a/src/main/scala/vexriscv/GenCoreDefault.scala b/src/main/scala/vexriscv/GenCoreDefault.scala
index de6e9bd..9ff02b0 100644
--- a/src/main/scala/vexriscv/GenCoreDefault.scala
+++ b/src/main/scala/vexriscv/GenCoreDefault.scala
@@ -12,8 +12,9 @@ import scala.collection.mutable.ArrayBuffer
 
 object SpinalConfig extends spinal.core.SpinalConfig(
   defaultConfigForClockDomains = ClockDomainConfig(
-    resetKind = spinal.core.SYNC
-  )
+    resetKind = spinal.core.ASYNC
+  ),
+  mergeAsyncProcess = false
 ){

```

**Comment by smunaut** [comment] 2019-05-18 16:58
never mind ... I had to erase my ~/.sbt directory, for some reason it wouldn't pickup the updated sources ...

**Comment by Dolu1990** [comment] 2019-05-18 17:03
I'm currently releasing a SpinalHDL version which do the mergeAsyncProcess  by default, then i will update VexRiscv to use  that spinalhdl version, and then merge it back to VexRiscv-verilog :)


Hoo damned, i'm sorry,  your patch is right.

```scala
object SpinalConfig extends spinal.core.SpinalConfig(
  defaultConfigForClockDomains = ClockDomainConfig(
    resetKind = spinal.core.SYNC
  ),
  mergeAsyncProcess = false
){
  //Insert a compilation phase which will add a  (* ram_style = "block" *) on all synchronous rams.
  phasesInserters += {(array) => array.insert(array.indexWhere(_.isInstanceOf[PhaseAllocateNames]) + 1, new ForceRamBlockPhase)}
}
```

I will let's you know when the release process is done.

**Comment by smunaut** [comment] 2019-05-18 17:41
I'd still like to be able to change config stuff myself, but AFAICT my changes have no effect whatsoever :/   I'm not sure what I'm doing wrong.

(for instance, I'd like ASYNC reset because that works way better on the ice40, I also wanted to disable all the catch illegal access / illegal instructions etc ... I'd rather save the logic than be 100% compliant)

**Comment by Dolu1990** [comment] 2019-05-18 18:33
@smunaut  Ahhh the issue with not updated generation is gone ?

Personnaly, just running things over and over update each time. For instance 

sbt compile "runMain vexriscv.GenCoreDefault --iCacheSize 0 --dCacheSize 0 --mulDiv false --singleC
ycleMulDiv false --bypass false --prediction none --outputFile VexRiscv_Min"

Maybe a "sbt clean" can help if the thing is buggy

**Comment by smunaut** [comment] 2019-05-18 18:35
Turned out to be a permission issue, it would just not overwrite the output ...

**Comment by Dolu1990** [comment] 2019-05-18 19:32
Ok :D

I released the fix and merged it in VexRiscv-verilog.
Let's me know if you have other issues.

**Closed by Dolu1990** 2019-05-18 19:32 UTC
